import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Headers from '@/component/Header/Headers'
import Widgets from '@/component/Main/Widgets'
import Footer from '@/component/Footer/Footer'
// import { useDispatch } from 'react-redux'
// import { useEffect } from 'react'
// import { widgetState } from '@/redux/WigetsSlice'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Headers/>
     <Widgets/>
     <Footer/>
    </>
  )
}
